// GENERATED by Filament.Generator from App.razor. DO NOT EDIT.
//
// Compiled from pure .razor: the template AND the @code block (Phase 3).
// State is lifted -- a private field the template reads and something assigns
// becomes a Signal -- and no user text is spliced anywhere in this file.

import { signal, batch, setAttr, listen, insert, list } from '../../src/filament-runtime/src/index.ts';

export function mount(target) {
  // -- @code: state and behaviour, compiled from C# ---------------------------
  const _rows = [];
  const _rowsVersion = signal(0);

  function _rowsChanged() {
    _rowsVersion.value++;
  }

  let _next = 1;

  function del(id) {
    for (let i = _rows.length - 1; i >= 0; i--) {
      if (_rows[i].id === id) {
        _rows.splice(i, 1);
        _rowsChanged();
      }
    }
  }

  // -- create(): the tree, built detached -------------------------------------
  const _el0 = document.createElement('ul');
  _el0.id = 'list';
  const _el1 = document.createElement('button');
  _el1.id = 'add';
  insert(_el1, document.createTextNode('add'));
  insert(_el0, _el1);

  // -- bindings ---------------------------------------------------------------
  function createR(r) {
    const _el2 = document.createElement('li');
    const _el3 = document.createElement('span');
    setAttr(_el3, 'class', 'lbl');
    insert(_el3, document.createTextNode(r.label));
    insert(_el2, _el3);
    const _el4 = document.createElement('button');
    setAttr(_el4, 'class', 'del');
    insert(_el4, document.createTextNode('x'));
    insert(_el2, _el4);
    listen(_el4, 'click', () => batch(() => {
    del(r.id);
  }));
    return _el2;
  }
  list(_el0, () => {
    _rowsVersion.value;
    return _rows;
  }, (r) => r.id, createR, null);

  // -- events -----------------------------------------------------------------
  listen(_el1, 'click', () => {
    const r = { id: _next, label: 'task ' + _next };
    _next = _next + 1;
    _rows.push(r);
    _rowsChanged();
  });

  // -- attach: last, so the effects' first run made no MutationRecord ----------
  insert(target, _el0);
}
