using System.Text;

namespace Filament.Generator;

/// <summary>
/// THE ROUTER (decision 139) — the one spec §3 non-goal that could not be erased.
///
/// Every other framework feature this compiler admits turns out to be a LOOKUP it can perform at build
/// time and then delete: @ref is a naming decision, JS interop is a direct call, a cascade is lexical
/// scope, generics erase, @inherits merges text. Routing is not like them, and the difference is not a
/// matter of effort. A route must be matched against a URL that only exists while the page is running,
/// re-matched when the user navigates, and un-mounted and re-mounted as it changes. That is BEHAVIOUR,
/// and behaviour has to be somewhere at run time.
///
/// SO IT IS GENERATED INTO THE APP, NEVER ADDED TO THE RUNTIME, and that placement is the whole point:
///
///   - the shared signals runtime stays byte-frozen at 1,943 B, so C1's budget is untouched and every
///     app that does NOT route pays exactly nothing for the fact that routing exists;
///   - the cost lands in the app that asked for it, where it is visible on the wire and MEASURED
///     (BENCH n°57). A routing slice that reported no weight change would have measured the wrong thing.
///
/// The emitted router is deliberately small and deliberately readable. It does four things, and each is
/// there because leaving it out is a bug a user would hit immediately:
///
///   1. MATCH the current pathname against the routes, falling back to the catch-all if one is declared.
///   2. MOUNT the match into the target, clearing what was there — a router that appends rather than
///      replaces shows two pages at once on the first navigation.
///   3. INTERCEPT same-origin link clicks and push history instead of letting the browser reload. Without
///      this, "navigation" is a full page load and the SPA is a multi-page app with extra steps.
///   4. LISTEN for popstate, so Back works. A router that only handles clicks strands the user.
/// </summary>
public static class RouterEmitter
{
    /// <param name="Module">the page module's import specifier, e.g. "./Home.g.js"</param>
    /// <param name="Route">the route the page declared, e.g. "/about"</param>
    /// <param name="Local">the local name its mount is imported as, e.g. "mountHome"</param>
    public readonly record struct Page(string Module, string Route, string Local);

    /// <summary>
    /// The router module. It IMPORTS each page rather than inlining it, so every page keeps compiling
    /// exactly as it does standalone — routing changes how pages are ASSEMBLED, not how they are
    /// compiled, and a page module is byte-identical whether or not it is routed.
    /// </summary>
    public static string Emit(IReadOnlyList<Page> pages)
    {
        if (pages.Count == 0)
            throw new GeneratorException("FIL-WIRING: the router was asked to emit with no pages.");

        var sb = new StringBuilder();

        sb.Append("// GENERATED by Filament.Generator. DO NOT EDIT.\n");
        sb.Append("//\n");
        sb.Append("// The router for this app, compiled from the @page directives of the components below.\n");
        sb.Append("// It is generated INTO THE APP on purpose: routing is the one feature that needs code at\n");
        sb.Append("// run time, and putting it here keeps the shared signals runtime byte-frozen, so an app\n");
        sb.Append("// that does not route pays nothing for the fact that routing exists.\n\n");

        foreach (var p in pages)
            sb.Append($"import {{ mount as {p.Local} }} from '{p.Module}';\n");

        sb.Append("\nconst routes = [\n");
        foreach (var p in pages)
            sb.Append($"  [{Js(p.Route)}, {p.Local}],\n");
        sb.Append("];\n\n");

        sb.Append(
            """
            export function mount(target) {
              // The active page's target is cleared before the next one mounts: a router that APPENDS
              // shows two pages at once the moment anyone navigates.
              function render() {
                const path = location.pathname;
                const hit = routes.find(([r]) => r === path) ?? routes.find(([r]) => r === '*');
                target.textContent = '';
                if (hit) hit[1](target);
              }

              // Same-origin links become history pushes. Without this, every link is a full page load and
              // the app is a multi-page app with extra steps. External links are left alone, and so are
              // modified clicks (ctrl/meta/shift) -- those mean "open elsewhere" and are the user's.
              addEventListener('click', (e) => {
                if (e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
                const a = e.target.closest && e.target.closest('a[href]');
                if (!a || a.target || a.hasAttribute('download')) return;
                const url = new URL(a.getAttribute('href'), location.href);
                if (url.origin !== location.origin) return;
                e.preventDefault();
                if (url.pathname !== location.pathname) {
                  history.pushState(null, '', url.pathname);
                  render();
                }
              });

              // Back and Forward. A router that only handles clicks strands the user on the first Back.
              addEventListener('popstate', render);

              render();
            }

            """);

        return sb.ToString();
    }

    /// <summary>A JS string literal. Single-quoted to match every other emission in this compiler.</summary>
    static string Js(string s) => "'" + s.Replace("\\", "\\\\").Replace("'", "\\'") + "'";
}
