#!/usr/bin/env bash
#
# demo/build.sh — build the Filament browser demo (Counter, Rows, If).
#
# A DEV-MODE sibling of bench/build-filament.sh. It compiles each sample's .razor
# with Filament.Generator and bundles the emitted JS so the apps run in a browser.
# It is a VIEWER, NOT A MEASUREMENT: the bundle is UNMINIFIED and ships no gzip
# siblings, so it can never be mistaken for the C1 artifact. Real weights come
# from bench/build-filament.sh and bench/harness/bench.mjs -- never here.
#
# Output lands in demo/dist/<app>/ and is gitignored, exactly like the generated
# .g.js files and bench/publish/: nothing runnable is committed in this repo.
set -euo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
DIST="$REPO_ROOT/demo/dist"

# esbuild ships in the runtime's node_modules (pinned 0.28.1). Call the binary
# directly rather than via npx, so resolution does not depend on cwd.
ESBUILD="$REPO_ROOT/src/filament-runtime/node_modules/.bin/esbuild"

die() { printf '\nFAIL: %s\n' "$1" >&2; exit 1; }
log() { printf '\n==> %s\n' "$1"; }

[[ -x "$ESBUILD" ]] || die "esbuild not found at $ESBUILD
   Run: (cd src/filament-runtime && npm ci)"
command -v dotnet >/dev/null 2>&1 \
  || die "dotnet not on PATH; the demo compiles .razor with Filament.Generator."

# id | razor (rel) | entry main.js (rel) | generated .g.js (rel) | css source (rel, or '-') | title
APPS=(
  "counter|samples/Counter/Counter.razor|samples/filament-counter-gen/main.js|samples/filament-counter-gen/Counter.g.js|baseline/Counter.Blazor/wwwroot/css/app.css|Counter"
  "rows|baseline/Rows.Blazor/RowsApp.razor|samples/filament-rows-gen/main.js|samples/filament-rows-gen/Rows.g.js|baseline/Rows.Blazor/wwwroot/css/app.css|Rows"
  "if|samples/If/If.razor|samples/filament-if-gen/main.js|samples/filament-if-gen/If.g.js|-|If"
)

rm -rf "${DIST:?}"

for spec in "${APPS[@]}"; do
  IFS='|' read -r id razor entry gen css title <<< "$spec"
  out="$DIST/$id"
  mkdir -p "$out/css"

  [[ -f "$REPO_ROOT/$entry" ]] || die "missing entry module: $entry"
  grep -qF "$(basename "$gen")" "$REPO_ROOT/$entry" \
    || die "$entry does not import $(basename "$gen"); the demo would bundle a stale/absent module."

  log "$title  <-  $razor"

  # Generate: rm-then-emit so the .g.js can never be stale; verify from the artifact.
  rm -f "$REPO_ROOT/$gen"
  dotnet run --project "$REPO_ROOT/src/Filament.Generator" -c Release -- \
    "$REPO_ROOT/$razor" "$REPO_ROOT/$gen" \
    || die "the generator refused '$title'. A construct outside the subset MUST
     diagnose rather than emit wrong JS, so this exit code is the generator working.
     Read the diagnostic above; do not work around it."
  [[ -f "$REPO_ROOT/$gen" ]] || die "the generator exited 0 for '$title' but wrote no file."
  grep -q 'GENERATED by Filament.Generator' "$REPO_ROOT/$gen" \
    || die "$gen lacks the generator banner -- something other than Filament.Generator wrote it."

  # Bundle: DEV mode. Unminified, stats defined out, never weighed.
  "$ESBUILD" "$REPO_ROOT/$entry" --bundle --format=iife --target=es2022 \
    --define:__FILAMENT_STATS__=false --outfile="$out/app.js" --log-level=warning \
    || die "esbuild failed for '$title'."

  # Per-app shell: RELATIVE paths (no <base href>), so it works under any server root.
  cat > "$out/index.html" <<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>$title — Filament demo</title>
    <link rel="stylesheet" href="css/app.css" />
    <link rel="icon" href="data:," />
</head>
<body>
    <div id="app">Loading…</div>
    <script src="app.js"></script>
</body>
</html>
HTML

  # Stylesheet: reuse the app's baseline sheet, or a minimal one for If (no baseline exists).
  if [[ "$css" == "-" ]]; then
    cat > "$out/css/app.css" <<'CSS'
body { font-family: system-ui, sans-serif; margin: 2rem; line-height: 1.5; }
#wrap { display: flex; align-items: center; gap: .75rem; }
button { font: inherit; padding: .3rem .8rem; cursor: pointer; }
CSS
  else
    [[ -f "$REPO_ROOT/$css" ]] || die "missing stylesheet: $css"
    cp "$REPO_ROOT/$css" "$out/css/app.css"
  fi

  printf '    OK  %-8s ->  demo/dist/%s/app.js  (%s B, unminified)\n' \
    "$title" "$id" "$(wc -c < "$out/app.js" | tr -d ' ')"
done

log "Done. Serve the demo, then open the landing page:"
printf '    python3 -m http.server 8137 --directory demo\n'
printf '    open http://localhost:8137/\n\n'
printf 'NOTE: DEV build (unminified, no gzip siblings) -- NOT a measurement.\n'
printf '      C1/C3/C4 weights come from bench/build-filament.sh + bench/harness/bench.mjs.\n'
