// GENERATED by Filament.Generator from About.razor. DO NOT EDIT.
//
// Compiled from pure .razor: the template AND the @code block (Phase 3).
// State is lifted -- a private field the template reads and something assigns
// becomes a Signal -- and no user text is spliced anywhere in this file.

import { signal, effect, setText, setAttr, listen, insert } from '../../src/filament-runtime/src/index.ts';

export function mount(target) {
  // -- @code: state and behaviour, compiled from C# ---------------------------
  const n = signal(0);

  // -- create(): the tree, built detached -------------------------------------
  const _el0 = document.createElement('div');
  _el0.id = 'about';
  const _el1 = document.createElement('h2');
  insert(_el1, document.createTextNode('about'));
  insert(_el0, _el1);
  const _el2 = document.createElement('p');
  insert(_el2, document.createTextNode('The same .razor pages, two compilers.'));
  insert(_el0, _el2);
  const _el3 = document.createElement('button');
  _el3.id = 'about-count';
  insert(_el3, document.createTextNode('clicked '));
  const _tx0 = document.createTextNode('');
  insert(_el3, _tx0);
  insert(_el0, _el3);
  const _el4 = document.createElement('a');
  _el4.id = 'to-board';
  setAttr(_el4, 'href', '/');
  insert(_el4, document.createTextNode('board'));
  insert(_el0, _el4);

  // -- bindings ---------------------------------------------------------------
  effect(() => setText(_tx0, n.value));

  // -- events -----------------------------------------------------------------
  listen(_el3, 'click', () => {
    n.value++;
  });

  // -- attach: last, so the effects' first run made no MutationRecord ----------
  insert(target, _el0);
}
