// GENERATED by Filament.Generator from Board.razor. DO NOT EDIT.
//
// Compiled from pure .razor: the template AND the @code block (Phase 3).
// State is lifted -- a private field the template reads and something assigns
// becomes a Signal -- and no user text is spliced anywhere in this file.

import { signal, effect, batch, setText, setAttr, listen, insert, list } from '../../src/filament-runtime/src/index.ts';

export function mount(target) {
  // -- @code: state and behaviour, compiled from C# ---------------------------
  const model = { label: signal('') };
  const tasks = [];
  const tasksVersion = signal(0);

  function tasksChanged() {
    tasksVersion.value++;
  }

  const visible = signal([]);
  let filter = 0;
  const active = signal(0);
  const total = signal(0);
  let nextId = 1;

  function refresh() {
    total.value = tasks.length;
    active.value = tasks.filter(x => !x.done.value).length;
    if (filter === 1) {
      visible.value = tasks.filter(x => !x.done.value);
    } else {
      if (filter === 2) {
        visible.value = tasks.filter(x => x.done.value);
      } else {
        visible.value = tasks.filter(x => true);
      }
    }
  }

  function toggle(id) {
    for (let i = 0; i < tasks.length; i++) {
      if (tasks[i].id === id) {
        tasks[i].done.value = !tasks[i].done.value;
      }
    }
    refresh();
  }

  function remove(id) {
    for (let i = tasks.length - 1; i >= 0; i--) {
      if (tasks[i].id === id) {
        tasks.splice(i, 1);
        tasksChanged();
      }
    }
    refresh();
  }

  // -- create(): the tree, built detached -------------------------------------
  const _el0 = document.createElement('div');
  _el0.id = 'board';
  const _el1 = document.createElement('form');
  const _el2 = document.createElement('input');
  _el2.id = 'task-input';
  insert(_el1, _el2);
  const _el3 = document.createElement('button');
  _el3.id = 'task-add';
  setAttr(_el3, 'type', 'submit');
  insert(_el3, document.createTextNode('add'));
  insert(_el1, _el3);
  insert(_el0, _el1);
  insert(_el0, document.createTextNode('\n\n'));
  const _el4 = document.createElement('p');
  _el4.id = 'stats';
  const _el5 = document.createElement('span');
  _el5.id = 'active';
  const _tx0 = document.createTextNode('');
  insert(_el5, _tx0);
  insert(_el4, _el5);
  insert(_el4, document.createTextNode(' active / '));
  const _el6 = document.createElement('span');
  _el6.id = 'total';
  const _tx1 = document.createTextNode('');
  insert(_el6, _tx1);
  insert(_el4, _el6);
  insert(_el4, document.createTextNode(' total'));
  insert(_el0, _el4);
  insert(_el0, document.createTextNode('\n\n'));
  const _el7 = document.createElement('p');
  const _el8 = document.createElement('button');
  _el8.id = 'filter-all';
  insert(_el8, document.createTextNode('all'));
  insert(_el7, _el8);
  const _el9 = document.createElement('button');
  _el9.id = 'filter-active';
  insert(_el9, document.createTextNode('active'));
  insert(_el7, _el9);
  const _el10 = document.createElement('button');
  _el10.id = 'filter-done';
  insert(_el10, document.createTextNode('done'));
  insert(_el7, _el10);
  insert(_el0, _el7);
  const _if0 = document.createComment('');
  insert(_el0, _if0);
  const _el12 = document.createElement('ul');
  _el12.id = 'task-list';
  insert(_el0, _el12);
  insert(_el0, document.createTextNode('\n\n'));
  const _el18 = document.createElement('a');
  _el18.id = 'to-about';
  setAttr(_el18, 'href', '/about');
  insert(_el18, document.createTextNode('about'));
  insert(_el0, _el18);

  // -- bindings ---------------------------------------------------------------
  effect(() => { _el2.value = model.label.value; });
  effect(() => setText(_tx0, active.value));
  effect(() => setText(_tx1, total.value));
  function ifBody() {
    const _el11 = document.createElement('p');
    _el11.id = 'empty';
    insert(_el11, document.createTextNode('no tasks'));
    return _el11;
  }
  list(_el0, () => (total.value === 0) ? [0] : [], () => 0, ifBody, _if0);
  function createT(t) {
    const _el13 = document.createElement('li');
    const _el14 = document.createElement('span');
    setAttr(_el14, 'class', 'label');
    insert(_el14, document.createTextNode(t.label));
    insert(_el13, _el14);
    const _el15 = document.createElement('span');
    setAttr(_el15, 'class', 'state');
    const _tx2 = document.createTextNode('');
    insert(_el15, _tx2);
    insert(_el13, _el15);
    const _el16 = document.createElement('button');
    setAttr(_el16, 'class', 'toggle');
    insert(_el16, document.createTextNode('toggle'));
    insert(_el13, _el16);
    const _el17 = document.createElement('button');
    setAttr(_el17, 'class', 'remove');
    insert(_el17, document.createTextNode('remove'));
    insert(_el13, _el17);
    effect(() => setText(_tx2, t.done.value ? 'done' : 'todo'));
    listen(_el16, 'click', () => batch(() => {
    toggle(t.id);
  }));
    listen(_el17, 'click', () => batch(() => {
    remove(t.id);
  }));
    return _el13;
  }
  list(_el12, () => visible.value, (t) => t.id, createT, null);

  // -- events -----------------------------------------------------------------
  listen(_el2, 'change', (e) => { model.label.value = e.target.value; });
  listen(_el1, 'submit', (e) => {
    e.preventDefault();
    batch(() => {
      if (model.label.value === '') {
        return;
      }
      const t = { id: nextId, label: model.label.value, done: signal(false) };
      nextId = nextId + 1;
      tasks.push(t);
      tasksChanged();
      model.label.value = '';
      refresh();
    });
  });
  listen(_el8, 'click', () => batch(() => {
    filter = 0;
    refresh();
  }));
  listen(_el9, 'click', () => batch(() => {
    filter = 1;
    refresh();
  }));
  listen(_el10, 'click', () => batch(() => {
    filter = 2;
    refresh();
  }));

  // -- attach: last, so the effects' first run made no MutationRecord ----------
  insert(target, _el0);
}
