// GENERATED by Filament.Generator. DO NOT EDIT.
//
// The router for this app, compiled from the @page directives of the components below.
// It is generated INTO THE APP on purpose: routing is the one feature that needs code at
// run time, and putting it here keeps the shared signals runtime byte-frozen, so an app
// that does not route pays nothing for the fact that routing exists.

import { mount as mountBoard } from './Board.g.js';
import { mount as mountAbout } from './About.g.js';

const routes = [
  ['/', mountBoard],
  ['/about', mountAbout],
];

export function mount(target) {
  // The active page's target is cleared before the next one mounts: a router that APPENDS
  // shows two pages at once the moment anyone navigates.
  function render() {
    const path = location.pathname;
    const hit = routes.find(([r]) => r === path) ?? routes.find(([r]) => r === '*');
    target.textContent = '';
    if (hit) hit[1](target);
  }

  // Same-origin links become history pushes. Without this, every link is a full page load and
  // the app is a multi-page app with extra steps. External links are left alone, and so are
  // modified clicks (ctrl/meta/shift) -- those mean "open elsewhere" and are the user's.
  addEventListener('click', (e) => {
    if (e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
    const a = e.target.closest && e.target.closest('a[href]');
    if (!a || a.target || a.hasAttribute('download')) return;
    const url = new URL(a.getAttribute('href'), location.href);
    if (url.origin !== location.origin) return;
    e.preventDefault();
    if (url.pathname !== location.pathname) {
      history.pushState(null, '', url.pathname);
      render();
    }
  });

  // Back and Forward. A router that only handles clicks strands the user on the first Back.
  addEventListener('popstate', render);

  render();
}
