// smoke.mjs — the playground's BYTE-PARITY proof (decision 144).
//
// The claim "the unchanged generator, in your browser" is checked, not asserted: the same .razor
// source is compiled by the CLI (dotnet Filament.Generator.dll) and by the published WASM engine
// driven in headless Chromium, with the SAME runtime specifier, and the two emissions must be
// BYTE-IDENTICAL. Fixtures cover the load-bearing machinery: Counter (@onclick = the tag-helper
// chain; typed @code = the semantic model), ForeachList (list() + LINQ + decision 140), and a
// genuine refusal (ForeachStatic) whose FIL diagnostic must surface with the CLI's wording.
//
//   node playground/smoke.mjs <engine-url>     e.g. http://localhost:4576/index.html
//
// Exits nonzero on any divergence. Functional, not a timing measurement — CI-eligible.
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const { chromium } = require('../bench/harness/node_modules/playwright/index.js');

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const url = process.argv[2] ?? 'http://localhost:4576/index.html';
const RUNTIME_SPECIFIER = './filament.js';

const FIXTURES = [
  { name: 'Counter', file: 'baseline/Counter.Blazor/App.razor', expectOk: true },
  { name: 'ForeachList', file: 'baseline/ForeachList.Blazor/App.razor', expectOk: true },
  { name: 'ForeachStatic (refusal)', file: 'tests/Filament.Generator.Tests/Unsupported/Gate/ForeachStatic.razor', expectOk: false, expectDiag: 'unsupported-foreach' },
];

function cliCompile(file) {
  const dll = path.join(ROOT, 'src', 'Filament.Generator', 'bin', 'Release', 'net10.0', 'Filament.Generator.dll');
  const out = path.join(ROOT, 'samples', 'Counter', `.smoke-${Math.random().toString(36).slice(2)}.js`);
  try {
    execFileSync('dotnet', [dll, path.join(ROOT, file), out, '--runtime', RUNTIME_SPECIFIER], { stdio: ['ignore', 'pipe', 'pipe'] });
    return { ok: true, js: fs.readFileSync(out, 'utf8') };
  } catch (e) {
    return { ok: false, stderr: String(e.stderr ?? '') };
  } finally {
    if (fs.existsSync(out)) fs.unlinkSync(out);
  }
}

// channel 'chrome' = the SYSTEM Chrome (evergreen), not Playwright's pinned chromium 150: that
// build's older wasm engine trips a mono-interp assertion (interp.c:2737) the current stable does
// not. The engine targets evergreen browsers; the smoke must judge it in one.
const browser = await chromium.launch({ headless: true, channel: 'chrome', ignoreDefaultArgs: ['--disable-field-trial-config'] });
const page = await browser.newPage();
page.on('pageerror', (e) => console.error('[page error]', e.message));
page.on('console', (m) => console.error(`[console.${m.type()}]`, m.text().slice(0, 400)));
await page.goto(`${url}?smoke=${Date.now()}`, { waitUntil: 'domcontentloaded' });
await page.waitForFunction(() => !!window.filamentPlayground, null, { timeout: 240_000 });

let failures = 0;
for (const f of FIXTURES) {
  const source = fs.readFileSync(path.join(ROOT, f.file), 'utf8');
  const wasm = await page.evaluate(
    ([src, spec]) => window.filamentPlayground.compile(src, spec),
    [source, RUNTIME_SPECIFIER],
  );
  if (f.expectOk) {
    const cli = cliCompile(f.file);
    // The CLI header names the input file ("from App.razor"); the browser names its MEMFS copy
    // ("from Component.razor"). Neutralise ONLY that header line — every emitted code byte counts.
    const norm = (js) => js.replace(/^\/\/ GENERATED by Filament\.Generator from .*$/m, '// GENERATED');
    if (!wasm.ok) {
      console.error(`FAIL ${f.name}: browser refused what the CLI accepts:\n${(wasm.diagnostics || []).join('\n')}`);
      failures++;
    } else if (!cli.ok) {
      console.error(`FAIL ${f.name}: CLI refused: ${cli.stderr}`);
      failures++;
    } else if (norm(wasm.js) !== norm(cli.js)) {
      console.error(`FAIL ${f.name}: browser and CLI emissions DIFFER (${wasm.js.length} vs ${cli.js.length} B)`);
      failures++;
    } else {
      console.log(`ok   ${f.name}: byte-identical (${wasm.js.length} B, ${wasm.ms} ms in-browser)`);
    }
  } else {
    if (wasm.ok) {
      console.error(`FAIL ${f.name}: browser ACCEPTED a fixture the register refuses`);
      failures++;
    } else if (!(wasm.diagnostics || []).some((d) => d.includes(f.expectDiag))) {
      console.error(`FAIL ${f.name}: refusal lacks '${f.expectDiag}':\n${(wasm.diagnostics || []).join('\n')}`);
      failures++;
    } else {
      console.log(`ok   ${f.name}: refused with ${f.expectDiag}, CLI wording intact (${wasm.ms} ms)`);
    }
  }
}

await browser.close();
if (failures) { console.error(`\n${failures} parity failure(s)`); process.exit(1); }
console.log('\nbyte-parity smoke: ALL GREEN');
